// words_sv.h — generated by johniak-sv/generate.js. Do not edit by hand.
// Swedish 11×10 layout (the simulator's exact grid, 110 LEDs).
// REQUIRES in ClockDisplayHAL.h:  WIDTH = 11, HEIGHT = 10
// Drop-in replacement for the WORDS_TO_LEDS table in ClockDisplayHAL.cpp.

ClockDisplayHAL::WordMapping const ClockDisplayHAL::WORDS_TO_LEDS[] = {
    {"KLOCKAN", 103, 109},
    {"AR", 99, 100},
    {"FEM_MIN", 89, 91},
    {"TIO_MIN", 94, 96},
    {"TJUGO", 83, 87},
    {"KVART", 66, 70},
    {"OVER", 72, 75},
    {"I", 64, 64},
    {"HALV", 58, 61},
    {"HOUR_1", 44, 46},
    {"HOUR_2", 48, 50},
    {"HOUR_3", 41, 43},
    {"HOUR_4", 36, 39},
    {"HOUR_5", 22, 24},
    {"HOUR_6", 26, 28},
    {"HOUR_7", 30, 32},
    {"HOUR_8", 18, 21},
    {"HOUR_9", 14, 16},
    {"HOUR_10", 8, 10},
    {"HOUR_11", 0, 3},
    {"HOUR_12", 4, 7}
};
